%YAML:1.0
#########################################
#  图像选项
#########################################
# 数据库根目录位置：该目录下应该有rgb_index/和dep_index/两个文件夹，记录了rgb图与深度度
data_source: /home/y/code/dataset/slam
# 图像特征的检测算子与描述算子的名称
detector_name: FAST
descriptor_name: SIFT
# 数据的起始编号与结束编号
start_index: 1
end_index: 2001
# 是否在灰度图中处理数据：暂不支持颜色信息
grayscale: yes
# 最小匹配距离
match_min_dist: 5
# 每一次循环的等待时间（毫秒）
step_time: 10
# 发现关键帧时等待时间
step_time_keyframe: 100
# 相邻两帧的最大距离，超过此距离则放弃该帧
error_threshold: 0.8

# feature manager
#连续看见多少帧则记录至仓库
save_if_seen: 1
# 新特征，未连续出现多少帧则从缓存删除（建议该参数设置大一些，以实现全局匹配）
del_not_seen: 20
# 是否为没有深度数据的点设置最大深度
set_max_depth: yes
# 最大深度
max_depth: 20
# 每一帧最最多匹配的路标上限
max_landmark_per_loop: 100

#########################################
#  图优化选项
#########################################
# 优化步数
optimize_step: 10
# robust核函数
robust_kernel: Cauchy
# 最大位移，超过此位移后需要全局优化,认为出现关键帧
max_pos_change: 0.2

#########################################
#  其他选项
#########################################
# 是否在线生成点云图（较耗时间）
online_pcl: yes
# 栅格大小
grid_leaf: 0.002
# 是否使用FAB-MAP 2.0
fabmap: no
