%YAML:1.0
#########################################
#  图像选项
#########################################
# 数据库根目录位置：该目录下应该有rgb_index/和dep_index/两个文件夹，记录了rgb图与深度图
data_source: /home/x/code/dataset/9_14_loop
# 图像特征的检测算子与描述算子的名称
detector_name: STAR
descriptor_name: SIFT
# 数据的起始编号与结束编号
start_index: 50
end_index: 724
# 两帧相邻图像描述子之间最小匹配距离
match_min_dist: 5
# 每一次循环的等待时间（毫秒）
step_time: 10


#########################################
#  图优化选项
#########################################
# 优化步数
optimize_step: 200
# robust核函数
robust_kernel: Cauchy
# 最大位移，超过此位移后需要全局优化,认为出现关键帧
max_pos_change: 0.25

#########################################
#  PCL
#########################################
# 栅格大小
grid_leaf: 0.03

#########################################
#  3D SLAM 选项
#########################################
# 相邻两帧的最大距离，超过此距离则放弃该帧
error_threshold: 0.8
# 提取平面时的距离阈值 （越大表示平面的精度越粗糙）
distance_threshold: 0.01
# 平面点的百分比
plane_percent: 0.3
# 归类图像点时的误差阈值（较大时会把离平面较远的点也算在平面上）
min_error_plane: 0.005
# 最大平面数量
max_planes: 4
# 是否使用闭环
loop_closure_detection: yes
# 闭环检测随机取多少帧
loopclosure_frames: 10
# 闭环检测误差阈值（离过去关键帧某个距离之内才算正确的闭环）
loop_closure_error: 1.0
# 丢失判定（连续若干帧以上匹配不到算作丢失）
lost_frames: 5
# 是否使用里程计
use_odometry: yes
# 里程计误差
error_odometry: 0.03

#########################################
#  相机参数
#########################################
# my robot
#camera_fx: 535.147
#camera_fy: 535.04
#camera_cx: 297.25
#camera_cy: 247.91
#camera_factor: 1000.0
# default
camera_fx: 525.00
camera_fy: 525.00
camera_cx: 319.50
camera_cy: 235.50
camera_factor: 1000.0
# fr1
#camera_fx: 517.0
#camera_fy: 517.0
#camera_cx: 318.6
#camera_cy: 255.3
#camera_factor: 5000.0
# fr2
#camera_fx: 520.9
#camera_fy: 521.0
#camera_cx: 325.1
#camera_cy: 249.7
#camera_factor: 5000.0
# fr3
#camera_fx: 535.9
#camera_fy: 539.2
#camera_cx: 320.1
#camera_cy: 247.6
#camera_factor: 5000.0
